name: deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22.2.0

      - name: Install dependencies
        run: yarn

      - name: Build app
        run: yarn build

      - name: Copy to Digital Ocean
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ".,!node_modules,!.git,!.github"
          target: "~/app"
          overwrite: true

      - name: Install dependecies, Sync Database and Restart app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/app
            yarn
            yarn prisma db push
            pm2 restart proffy-api
